version: '3.9'

services:
  paymentapp:
    container_name: payment
    build:
      dockerfile: Dockerfile
    command: ./wait-for-postgres.sh paymentdb ./bin/api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - paymentdb
    restart: always
    networks:
      - backend
  
  paymentdb:
    image: postgres:15.1
    container_name: paymentdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=paymentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paymentdb
    volumes:
      - ./migrations/000001_paymentdb.up.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

volumes:
  migrations:
networks:
  backend:
    driver: bridge